### ISSUE TITLE
Multi-file SPARQL support

### ISSUE THREAD

**Issue by linonetwo** [inrupt/pod-server#19]
Currently, NSS doesn't support multi-file search (run SPARQL on all file inside a container on the server side), but it can be super convenient when designing app. 

Will you support it?

Will it be backend specific (for example only when the backend is NEO4J)?

**Comment by michielbdejong** [comment]
Sure, that could be useful but my personal view is that it breaks the 'web of data' vision a little bit if you query per host instead of per (linked) resource.

**Comment by michielbdejong** [comment]
Sure, those hooks are there, in the sense that you could add a new [operationHandler](https://github.com/inrupt/wac-ldp/blob/3304cc7b9c4a1ca72df984b08a9e294ca8842b33/src/lib/core/WacLdp.ts#L48) that combines the looping-over-a-container from https://github.com/inrupt/wac-ldp/blob/c917c2e0974cc540f1cd4fc07860fad18b50dc85/src/lib/operationHandlers/globReadHandler.ts#L35 with the sparql-querying from https://github.com/inrupt/wac-ldp/blob/c917c2e0974cc540f1cd4fc07860fad18b50dc85/src/lib/operationHandlers/readBlobHandler.ts#L71. Will close this issue here now, let us know if you want to try this and if I or @jaxoncreed can help you with that!
